baseURL = 'https://shvier.github.io'
languageCode = 'en-us'
title = "Barry's Site"
theme = 'paper'
paginate = 10

enableGitInfo = true
[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = ['lastmod', ':fileModTime', ':git', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']

[params]
  twitter = 'shvier1894'
  github = 'Shvier'
  math = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[services]
  [services.twitter]
    disableInlineCSS = true
